[package]
name = "banditdb"
version = "0.1.0"
edition = "2021"

[dependencies]
prettytable = "0.10.0"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
sled = "0.34.7"
bincode = "2.0.0-rc.3"
